;; This "home-environment" file can be passed to 'guix home reconfigure'
;; to reproduce the content of your profile.  This is "symbolic": it only
;; specifies package names.  To reproduce the exact same profile, you also
;; need to capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(use-modules (gnu home)
             (gnu packages)
             (gnu services)
             (guix gexp)
             (gnu home services desktop)
             (gnu home services xdg)
             (gnu home services syncthing)
             (gnu home services sound)
             (gnu home services fontutils))

(define user-config
  (list
    (simple-service 'additional-fonts-service
                    home-fontconfig-service-type
                    '((alias (@ (binding strong))
                             (family serif)
                             (prefer (family "Noto Serif") (family "Latin Modern Roman")))
                      (alias (@ (binding strong))
                             (family sans-serif)
                             (prefer (family "Noto Sans") (family "Latin Modern Sans")))
                      (alias (@ (binding strong))
                             (family monospace)
                             (prefer (family "Noto Sans Mono") (family "Latin Modern Mono")))
                      (alias (@ (binding strong))
                             (family system-ui)
                             (prefer (family sans-serif)))

                      (match (@ (target pattern))
                             (test (@ (name family)) "serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK SC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "ja")
                             (test (@ (name family)) "serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK JP"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "ko")
                             (test (@ (name family)) "serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK KR"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh")
                             (test (@ (name family)) "serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK SC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-hans")
                             (test (@ (name family)) "serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK SC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-hant")
                             (test (@ (name family)) "serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK TC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-cn")
                             (test (@ (name family)) "serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK SC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-tw")
                             (test (@ (name family)) "serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK TC"))

                      (match (@ (target pattern))
                             (test (@ (name family)) "sans-serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK SC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "ja")
                             (test (@ (name family)) "sans-serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK JP"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "ko")
                             (test (@ (name family)) "sans-serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK KR"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh")
                             (test (@ (name family)) "sans-serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK SC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-hans")
                             (test (@ (name family)) "sans-serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK SC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-hant")
                             (test (@ (name family)) "sans-serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK TC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-hant-hk")
                             (test (@ (name family)) "sans-serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK HK"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-cn")
                             (test (@ (name family)) "sans-serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK SC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-tw")
                             (test (@ (name family)) "sans-serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK TC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-hk")
                             (test (@ (name family)) "sans-serif")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK HK"))

                      (match (@ (target pattern))
                             (test (@ (name family)) "monospace")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK SC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "ja")
                             (test (@ (name family)) "monospace")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK JP"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "ko")
                             (test (@ (name family)) "monospace")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK KR"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh")
                             (test (@ (name family)) "monospace")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK SC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-hans")
                             (test (@ (name family)) "monospace")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK SC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-hant")
                             (test (@ (name family)) "monospace")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK TC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-hant-hk")
                             (test (@ (name family)) "monospace")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK HK"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-cn")
                             (test (@ (name family)) "monospace")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK SC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-tw")
                             (test (@ (name family)) "monospace")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK TC"))
                      (match (@ (target pattern))
                             (test (@ (name lang) (compare contains)) "zh-hk")
                             (test (@ (name family)) "monospace")
                             (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK HK"))))
    (service home-xdg-mime-applications-service-type
             (home-xdg-mime-applications-configuration
               (default '((image/jpeg . nsxiv.desktop)))
               (desktop-entries
                 (list

                   (xdg-desktop-entry
                     (file "poweroff")
                     (name "Power Off")
                     (type 'application)
                     (config '((exec . "shutdown"))))
                   (xdg-desktop-entry
                     (file "reboot")
                     (name "Reboot")
                     (type 'application)
                     (config '((exec . "reboot"))))

                   (xdg-desktop-entry
                     (file "nsxiv")
                     (name "nsxiv")
                     (type 'application)
                     (config '((exec . "nsxiv %F")
                               (MimeType . "image/bmp;image/gif;image/jpeg;image/jpg;image/png;image/tiff;image/x-bmp;image/x-portable-anymap;image/x-portable-bitmap;image/x-portable-graymap;image/x-tga;image/x-xpixmap;image/webp;image/heic;image/svg+xml;application/postscript;image/jp2;image/jxl;image/avif;image/heif;")
                               (NoDisplay . "true")
                               (GenericName . "Image Viewer")
                               )))
                   ))))
    ))


(define user-apps
  (list
    (service home-syncthing-service-type)
    ))

(define user-sys
  (list
    (service home-dbus-service-type)
    (service home-pipewire-service-type)
    (simple-service 'additional-dbus-services home-dbus-service-type
                    (map specification->package (list "xdg-desktop-portal-wlr" "xdg-desktop-portal" "blueman")))
    ))

(home-environment
  (services
    (append user-config
            user-apps
            user-sys ;; TODO only if using sway
            %base-home-services)))
