;; This "home-environment" file can be passed to 'guix home reconfigure'
;; to reproduce the content of your profile.  This is "symbolic": it only
;; specifies package names.  To reproduce the exact same profile, you also
;; need to capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(use-modules (gnu home)
             (gnu packages)
             (gnu services)
             (guix gexp)
             (gnu home services desktop)
             (gnu home services syncthing)
             (gnu home services sound)
             (gnu home services fontutils))

(home-environment
  (services
    (append (list (service home-syncthing-service-type)
                  (service home-dbus-service-type)
                  (service home-pipewire-service-type)
                  (simple-service 'additional-fonts-service
                                  home-fontconfig-service-type
                                  '((alias (@ (binding strong))
                                           (family serif)
                                           (prefer (family "Noto Serif") (family "Latin Modern Roman")))
                                    (alias (@ (binding strong))
                                           (family sans-serif)
                                           (prefer (family "Noto Sans") (family "Latin Modern Sans")))
                                    (alias (@ (binding strong))
                                           (family monospace)
                                           (prefer (family "Noto Sans Mono") (family "Latin Modern Mono")))
                                    (alias (@ (binding strong))
                                           (family system-ui)
                                           (prefer (family sans-serif)))

                                    (match (@ (target pattern))
                                           (test (@ (name family)) "serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "ja")
                                           (test (@ (name family)) "serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK JP")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "ko")
                                           (test (@ (name family)) "serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK KR")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh")
                                           (test (@ (name family)) "serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-hans")
                                           (test (@ (name family)) "serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-hant")
                                           (test (@ (name family)) "serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK TC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-cn")
                                           (test (@ (name family)) "serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-tw")
                                           (test (@ (name family)) "serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Serif CJK TC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name family)) "sans-serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "ja")
                                           (test (@ (name family)) "sans-serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK JP")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "ko")
                                           (test (@ (name family)) "sans-serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK KR")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh")
                                           (test (@ (name family)) "sans-serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-hans")
                                           (test (@ (name family)) "sans-serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-hant")
                                           (test (@ (name family)) "sans-serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK TC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-hant-hk")
                                           (test (@ (name family)) "sans-serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK HK")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-cn")
                                           (test (@ (name family)) "sans-serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-tw")
                                           (test (@ (name family)) "sans-serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK TC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-hk")
                                           (test (@ (name family)) "sans-serif")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK HK")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name family)) "monospace")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "ja")
                                           (test (@ (name family)) "monospace")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK JP")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "ko")
                                           (test (@ (name family)) "monospace")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK KR")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh")
                                           (test (@ (name family)) "monospace")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-hans")
                                           (test (@ (name family)) "monospace")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-hant")
                                           (test (@ (name family)) "monospace")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK TC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-hant-hk")
                                           (test (@ (name family)) "monospace")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK HK")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-cn")
                                           (test (@ (name family)) "monospace")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-tw")
                                           (test (@ (name family)) "monospace")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK TC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-hk")
                                           (test (@ (name family)) "monospace")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans Mono CJK HK")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name family)) "system-ui")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "ja")
                                           (test (@ (name family)) "system-ui")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK JP")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "ko")
                                           (test (@ (name family)) "system-ui")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK KR")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh")
                                           (test (@ (name family)) "system-ui")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-hans")
                                           (test (@ (name family)) "system-ui")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-hant")
                                           (test (@ (name family)) "system-ui")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK TC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-hant-hk")
                                           (test (@ (name family)) "system-ui")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK HK")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-cn")
                                           (test (@ (name family)) "system-ui")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK SC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-tw")
                                           (test (@ (name family)) "system-ui")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK TC")
                                           )

                                    (match (@ (target pattern))
                                           (test (@ (name lang) (compare contains)) "zh-hk")
                                           (test (@ (name family)) "system-ui")
                                           (edit (@ (name family) (mode append) (binding strong)) "Noto Sans CJK HK")
                                           )
                                    ))

            (simple-service 'additional-dbus-services home-dbus-service-type (map specification->package (list "xdg-desktop-portal-wlr" "xdg-desktop-portal" "blueman")))
            ) %base-home-services)))
