[theme]
theme = "solarized-dark"
[icons]
icons = "awesome6"
[icons.overrides]

[[block]]
block = "cpu"
format = "$icon $barchart $boost"

[[block]]
block = "memory"
format = "$icon $mem_used_percents"
format_alt = "$icon $mem_used.eng(w:3) / $mem_total.eng(w:3)"

[[block]]
block = "battery"
format = " $icon $percentage ($time) $power.eng(w:4)"
full_format = " $icon $percentage ($time) $power.eng(w:4)"
empty_format = " $icon $percentage ($time) $power.eng(w:4)"
not_charging_format = " $icon $percentage (Not Charging) $power.eng(w:4)"
driver = "upower"


[[block]]
block = "net"
format = "$icon {$signal_strength $ssid|Wired connection}"
format_alt = "$icon {$signal_strength $ssid|Wired connection} ($device) ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K)"

[[block]]
block = "backlight"
root_scaling = 2.4

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
